### PR TITLE
Instructions for Lowin

### PR DESCRIPTION
**Pull request by ilievski-david**
## Changes to be done **[DONE]**

**1.** /docker/Dockerfile  **[DONE]**

- [Line 28] The docker image should have an entry point, when we call the docker image it needs to imidiatly call the inference.py and initiate rendering. On Iexec you do not have control while the docker image is running. You call it with your args, it executes, dumps everything to iexec_out and that's it. The inference script should stop when finished so IExec knows the results are finished.

**2.** /src/stable-diffusion-quantized/model/inference **[DONE]**

- [Line 14] The output is constant in iexec and it is retrieved using os.environ['IEXEC_OUT']
- [Line 15-24] here is no prompt on iexec. You call it with what are here system args. You can have many system args and the way you distinguish between is the order.

    sys.argv[1] can be the prompt
    sys.argv[2] can be the inference step
    sys.argv[3] can be the hight of the image
    sys.argv[4] can be the width of the image

- [Line 39-40] The way Iexec works is you can have your app executed by multiple workers at the same time. This is for apps that need result integrity, not for us. Because you can't trust one worker, he can be malicious, you run the app at once on +3 workers and iexec compares the final file, if all workers retrieve the same result it means there wasn't malicious activity. This is not for us as the images are not crucial, and even if we want we can't because Machine Learning models often use randoms and it is not deteremistic. So running it on 3 computers will yield 3 different results.

## How should you run it.

docker run \
 -v /Users/id/Documents/projects/stable-diffusion-quantized/io/iexec_in:/iexec_in \
 -v /Users/id/Documents/projects/stable-diffusion-quantized/io/iexec_out:/iexec_out \
 -e IEXEC_IN=/iexec_in \
 -e IEXEC_OUT=/iexec_out \
 lowinli98/stable-diffusion-quantized arg1 arg2 arg3 arg4

### CODE REVIEW

**Comment by LowinLi** [comment]
I add new content to .gitignore and .dockerignore, exclude png images in git.

**Comment by ilievski-david** [comment]
I had to add a placeholder file in the iexec_out folder. Git won't register an empty directory.

**Comment by ilievski-david** [comment]
# Iexec compatible 
I added everything to make it iexec compatible and it should work on first run.

## Task for Lowlin
- Pull the branch, build the image, run it using the instructions in the updated readme, push the image if it works.

##  Note
Screenshot 2023-12-10 at 21 27 45
Screenshot 2023-12-10 at 21 28 12


- When entering the prompt as an arg to docker run, we can't use spaces at the moment i used underscores at the moment. I am in contact with iexec for a solution.  Worst case scenario i will write a script to change the underscores to spaces.

## What I did:
- I added the inference.py as an entry point to the docker image (Dockerfile LINE 28)
- I changed the important stuff in the inference.py to accept the prompt, inference steps, height and width from docker args
- I added the required computed.json to be written in the iexec_in directory
- Changed the readme for instructions on how to run it


P.S. I can't build the image on my machine. The prepare layer that fails on my machine does not get cached even after pull, retag to my local docker. If you build it with this push, we are ready for the demo.

**Comment by LowinLi** [comment]
图片

+ I have fix some script, and it works.

**Pull request merged**
